### ISSUE TITLE
swipe function throws error 

### ISSUE THREAD

**Issue by debasisj** [AppiumTestDistribution/appium-gestures-plugin#64]
org.openqa.selenium.InvalidArgumentException: Parameters were incorrect. We wanted {"required":["elementId","percentage"]} and you sent ["percentage","elementId","direction"]
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [d2ea2f84-ded3-4b0d-9dc4-06029ec16ebd, swipe {percentage=50, elementId=00000000-0000-0362-ffff-ffff00000047, direction=up}]
Capabilities {appium:appActivity: com.vfm.MainActivity, appium:appPackage: com.vfm.sit, appium:automationName: UiAutomator2, appium:databaseEnabled: false, appium:desired: {appActivity: com.vfm.MainActivity, appPackage: com.vfm.sit, automationName: UiAutomator2, deviceName: emulator-5554, platformName: android, uiautomator2ServerReadTimeout: 10000}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone64_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2400, appium:deviceUDID: emulator-5554, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 136, appium:takesScreenshot: true, appium:uiautomator2ServerReadTimeout: 10000, appium:viewportRect: {height: 2065, left: 0, top: 136, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: d2ea2f84-ded3-4b0d-9dc4-06029ec16ebd
 
              at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
              at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
              at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
              at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
              at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
              at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
              at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
              at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
              at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
              at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
              at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
              at org.tfa.appiumwrapper.MobileHelper.scroll(MobileHelper.java:84)
              at Screens.ProfileScreen.scrollToCommPreferences(ProfileScreen.java:63)
              at StepDefinitions.MyProfile.scrollToMyCommsPreferences(MyProfile.java:37)
              at ✽.Scroll to my comms preferences(file:///C:/Users/djagadeb/Repos/qe-automation-java-senchuri/VFM/src/test/resources/TestFeatures/LoginAndViewProfileDetails.feature:12)

**Comment by saikrishna321** [comment]
Please show your client code
