### ISSUE TITLE
.withArgument(GeneralServerFlag.USE_PLUGINS, "gestures,element-wait") causing connection problem with apple device

### ISSUE THREAD

**Issue by vnuta9** [AppiumTestDistribution/appium-gestures-plugin#83]
I am using the following method to invoke the Appium Server and connect to Android and Apple devices.  
 
```
public AppiumDriverLocalService GetAppiumService(){
        GlobalParams params = new GlobalParams();
        return AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                .withIPAddress("127.0.0.1")
                .withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
                .usingDriverExecutable(new File("/usr/local/bin/node"))
                .usingAnyFreePort() //.usingPort(4723)
                .withTimeout(Duration.ofSeconds(40)) // to prevent failing to startLocally error
//                .withArgument(GeneralServerFlag.USE_PLUGINS, "gestures,element-wait") // <<<------- or comma separated list
//                .withArgument(GeneralServerFlag.USE_PLUGINS, "element-wait")  // <<<-------
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE) // session clobbering. new session takes over even the old still running
                .withArgument(GeneralServerFlag.LOCAL_TIMEZONE)
                .withLogFile(new File(params.getPlatformName() + "_"+ params.getDeviceName() + File.separator + "Server.log")));
}
```

With Android device this line 
**withArgument(GeneralServerFlag.USE_PLUGINS, "gestures,element-wait")**  
is causing **NO** problem. But with apple device, it is causing this error...

` Given launch the app                          # stepdef.ActivationStepDef.launchTheApp()
  Given user is in landing page                 # stepdef.ActivationStepDef.userIsInLandingPage()
      org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'jwproxy')
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [6fb9f7ee-c3f9-41f7-936b-e05eb4f71848, findElement {using=accessibility id, value=Get Started}]
Capabilities {appium:automationName: XCuiTest, appium:bundleId: com.zimperium.zIPS, appium:databaseEnabled: false, appium:deviceName: iPhone, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 120, appium:takesScreenshot: true, appium:udid: 00008020-001428810A88002E, appium:updatedWDABundleId: com.zips.io, appium:wdaLocalPort: 10001, appium:webStorageEnabled: false, appium:xcodeOrgId: ZPBUXYR5Q9, appium:xcodeSigningId: iPhone Developer, platformName: IOS}
Session ID: 6fb9f7ee-c3f9-41f7-936b-e05eb4f71848
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:191)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:164)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:98)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:118)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.getAttribute(<generated>)
	at org.openqa.selenium.support.ui.ExpectedConditions.getAttributeOrCssValue(ExpectedConditions.java:1182)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:40)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1130)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1127)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at pages.BasePage.waitForVisibility(BasePage.java:131)
	at pages.BasePage.isDisplayed(BasePage.java:199)
	at pages.ActivationPage.verifyGetStartedBtn(ActivationPage.java:207)
	at stepdef.ActivationStepDef.userIsInLandingPage(ActivationStepDef.java:21)
	at ✽.user is in landing page(file:///Users/venkatanutalapati/dev/IntelliJWorkspace/zimperiumzips/src/test/resources/features/Dashboard.feature:8)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'jwproxy')
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [6fb9f7ee-c3f9-41f7-936b-e05eb4f71848, findElement {using=accessibility id, value=Get Started}]
Capabilities {appium:automationName: XCuiTest, appium:bundleId: com.zimperium.zIPS, appium:databaseEnabled: false, appium:deviceName: iPhone, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 120, appium:takesScreenshot: true, appium:udid: 00008020-001428810A88002E, appium:updatedWDABundleId: com.zips.io, appium:wdaLocalPort: 10001, appium:webStorageEnabled: false, appium:xcodeOrgId: ZPBUXYR5Q9, appium:xcodeSigningId: iPhone Developer, platformName: IOS}
Session ID: 6fb9f7ee-c3f9-41f7-936b-e05eb4f71848
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.pagefactory.bys.builder.ByChained.lambda$getSearchingFunction$0(ByChained.java:41)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.bys.builder.ByChained.findElement(ByChained.java:75)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:80)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElement(ContentMappedBy.java:50)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:80)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$findElement$0(AppiumElementLocator.java:119)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:171)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:164)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:98)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:118)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.getAttribute(<generated>)
	at org.openqa.selenium.support.ui.ExpectedConditions.getAttributeOrCssValue(ExpectedConditions.java:1182)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:40)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1130)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1127)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at pages.BasePage.waitForVisibility(BasePage.java:131)
	at pages.BasePage.isDisplayed(BasePage.java:199)
	at pages.ActivationPage.verifyGetStartedBtn(ActivationPage.java:207)
	at stepdef.ActivationStepDef.userIsInLandingPage(ActivationStepDef.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:110)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:110)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at runners.MyTestNGRunnerTest.scenario(MyTestNGRunnerTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

  And Create Group Activation Link              # stepdef.ActivationStepDef.createGroupActivation()
  When user selects "Get Started" option        # stepdef.ActivationStepDef.userSelectsOption(java.lang.String)
  And user selects "Login with Activation Link" # stepdef.ActivationStepDef.userSelects(java.lang.String)
  And user enters activation link               # stepdef.ActivationStepDef.userEntersActivationLink()
  And user taps "continue" option               # stepdef.ActivationStepDef.userTapsOption(java.lang.String)
  And user allows "All the Permission"          # stepdef.ActivationStepDef.userAllows(java.lang.String)
  And user allows device setting "permissions"  # stepdef.ActivationStepDef.userAllowsDeviceSetting(java.lang.String)
  Then user should see "DashBoard" page         # stepdef.ActivationStepDef.userShouldSeePage(java.lang.String)

org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'jwproxy')
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [6fb9f7ee-c3f9-41f7-936b-e05eb4f71848, findElement {using=accessibility id, value=Get Started}]
Capabilities {appium:automationName: XCuiTest, appium:bundleId: com.zimperium.zIPS, appium:databaseEnabled: false, appium:deviceName: iPhone, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 120, appium:takesScreenshot: true, appium:udid: 00008020-001428810A88002E, appium:updatedWDABundleId: com.zips.io, appium:wdaLocalPort: 10001, appium:webStorageEnabled: false, appium:xcodeOrgId: ZPBUXYR5Q9, appium:xcodeSigningId: iPhone Developer, platformName: IOS}
Session ID: 6fb9f7ee-c3f9-41f7-936b-e05eb4f71848

	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:191)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:164)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:98)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:118)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.getAttribute(<generated>)
	at org.openqa.selenium.support.ui.ExpectedConditions.getAttributeOrCssValue(ExpectedConditions.java:1182)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:40)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1130)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1127)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at pages.BasePage.waitForVisibility(BasePage.java:131)
	at pages.BasePage.isDisplayed(BasePage.java:199)
	at pages.ActivationPage.verifyGetStartedBtn(ActivationPage.java:207)
	at stepdef.ActivationStepDef.userIsInLandingPage(ActivationStepDef.java:21)
	at ✽.user is in landing page(file:///Users/venkatanutalapati/dev/IntelliJWorkspace/zimperiumzips/src/test/resources/features/Dashboard.feature:8)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'jwproxy')
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [6fb9f7ee-c3f9-41f7-936b-e05eb4f71848, findElement {using=accessibility id, value=Get Started}]
Capabilities {appium:automationName: XCuiTest, appium:bundleId: com.zimperium.zIPS, appium:databaseEnabled: false, appium:deviceName: iPhone, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 120, appium:takesScreenshot: true, appium:udid: 00008020-001428810A88002E, appium:updatedWDABundleId: com.zips.io, appium:wdaLocalPort: 10001, appium:webStorageEnabled: false, appium:xcodeOrgId: ZPBUXYR5Q9, appium:xcodeSigningId: iPhone Developer, platformName: IOS}
Session ID: 6fb9f7ee-c3f9-41f7-936b-e05eb4f71848
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.pagefactory.bys.builder.ByChained.lambda$getSearchingFunction$0(ByChained.java:41)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.bys.builder.ByChained.findElement(ByChained.java:75)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:80)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElement(ContentMappedBy.java:50)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:80)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$findElement$0(AppiumElementLocator.java:119)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:171)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:164)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:98)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:118)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.getAttribute(<generated>)
	at org.openqa.selenium.support.ui.ExpectedConditions.getAttributeOrCssValue(ExpectedConditions.java:1182)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:40)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1130)
	at org.openqa.selenium.support.ui.ExpectedConditions$40.apply(ExpectedConditions.java:1127)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at pages.BasePage.waitForVisibility(BasePage.java:131)
	at pages.BasePage.isDisplayed(BasePage.java:199)
	at pages.ActivationPage.verifyGetStartedBtn(ActivationPage.java:207)
	at stepdef.ActivationStepDef.userIsInLandingPage(ActivationStepDef.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:110)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:110)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at runners.MyTestNGRunnerTest.scenario(MyTestNGRunnerTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

`
I am not able to avail the plugin feature with apple device. Will you please suggest a solution or the cause of the problem, if I am doing some thing wrong ?

**Comment by saikrishna321** [comment]
Please use the latest element-wait plugin. This issue is fixed
